### ISSUE TITLE
Please publish app for arm64 and amd64, too

### ISSUE THREAD

**Issue by jonnius** [t-mon/swipeout#11]
Doing so is easy:

- [ ] Make sure you Clickable is up-to-date (should be >= 6.6)
- [ ] Make sure your Clickable images are up-to-date with `clickable update`
- [ ] Build for all architectures
```
clickable build --arch armhf
clickable build --arch arm64
clickable build --arch amd64
```
- [ ] Publish for all architectures
```
clickable publish --arch armhf --apikey <OPENSTORE_KEY>
clickable publish --arch arm64 --apikey <OPENSTORE_KEY>
clickable publish --arch amd64 --apikey <OPENSTORE_KEY>
```

**Comment by Anshorei** [comment]
Poke.

It would be very nice if you could do so! I've installed it using clickable, but others might not know they can do so.

**Comment by t-mon** [comment]
I updated all packages in the open-store. Please let me know if they work for you.
