### ISSUE TITLE
Sound settings of the phone are inappropriately changed by swipeout

### ISSUE THREAD

**Issue by pierrefrancois** [t-mon/swipeout#6]
Swipeout seems to record in some way the volume level of the phone, and when the game is played, that volume level is inappropriately restored after some moves, even after rebooting the phone.

**Comment by t-mon** [comment]
Thanks for the bug report. I checked the code. This is a known system issue. I have no influence on that behaviour in the application. Other applications using sound effects have the same problem with the volume control. You could switch of the sound effect in Swipeout if this is to annoying.

**Comment by t-mon** [comment]
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1478506
